import os
import re
import urllib.parse
from jsmin import jsmin

def build():
    # Configuration
    src_dir = "src"
    dist_dir = "dist"
    output_md = "BOOKMARKLETS.md"

    if not os.path.exists(dist_dir):
        os.makedirs(dist_dir)

    print("Starting Bookmarklet Build Process...")

    bookmarklets = []

    if not os.path.exists(src_dir):
        print(f"Error: Source directory '{src_dir}' not found!")
        return

    for filename in sorted(os.listdir(src_dir)):
        if filename.endswith(".js"):
            src_path = os.path.join(src_dir, filename)
            dist_path = os.path.join(dist_dir, filename.replace(".js", ".min.js"))
            
            print(f"Processing {filename}...")

            try:
                with open(src_path, "r", encoding="utf-8") as f:
                    lines = f.readlines()
                
                # Extract description (from the first line)
                description = ""
                if lines and lines[0].startswith("// Description:"):
                    description = lines[0].replace("// Description:", "").strip()
                    # Remove the description line for minification
                    code_to_minify = "".join(lines[1:])
                else:
                    code_to_minify = "".join(lines)
                
                # Minification
                minified_code = jsmin(code_to_minify).strip()
                
                # Save .min.js file
                with open(dist_path, "w", encoding="utf-8") as f:
                    f.write("javascript:" + minified_code)
                
                # URL-Encoding for Markdown
                safe_code_for_markdown = "javascript:" + urllib.parse.quote(minified_code, safe='()=;:,/')
                
                # Format Display Name (e.g., 'amazon-to-camel' -> 'Amazon To Camel')
                display_name = filename.replace(".js", "").replace("-", " ").title()
                
                # Assemble Markdown block
                entry = f"### {display_name}\n"
                if description:
                    entry += f"*{description}*\n\n"
                entry += f"- [Install {display_name}]({safe_code_for_markdown})\n"
                
                bookmarklets.append(entry)
                print(f"   Successfully minified.")

            except Exception as e:
                print(f"   Error processing {filename}: {e}")

    # Generate BOOKMARKLETS.md
    if bookmarklets:
        with open(output_md, "w", encoding="utf-8") as f:
            f.write("# Available Bookmarklets\n\n")
            f.write("This file is automatically generated. Drag the links below to your bookmarks bar to install them.\n\n")
            f.write("---\n\n")
            f.write("\n---\n".join(bookmarklets))
            
            # Timestamp for the footer
            import datetime
            timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            f.write(f"\n\n---\n*Last updated: {timestamp}*")
        
        print(f"\n'{output_md}' updated with {len(bookmarklets)} links.")
    
    print("\nBuild completed successfully!")

if __name__ == "__main__":
    build()